version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.worker
    working_dir: /app
    volumes:
      - ./astro-frontend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=developmentt 